client_config_backend: settings
client_config:
  client_id: 646824310779-3qkak68ihr1hhe0sb55lpcir0ip5el7a.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install